# Generated by Django 5.2.8 on 2025-11-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compras",
                to="crud_app.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
