# Generated by Django 5.2.8 on 2025-11-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app", "0002_alter_compra_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="crud_app.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
