# Generated by Django 5.2.8 on 2025-11-07 19:51

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    
    # Crear grupo 'Empleado'
    Group.objects.get_or_create(name='Empleado')
    
    # Crear grupo 'Gerente'
    Group.objects.get_or_create(name='Gerente')

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Empleado').delete()
    Group.objects.filter(name='Gerente').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_venta_cliente'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]