# Generated by Django 5.2.8 on 2025-11-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app", "0005_historicalproducto"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproducto",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de Eliminación"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de Eliminación"
            ),
        ),
    ]
