# Generated by Django 5.2.8 on 2025-11-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crud_app",
            "0011_venta_created_by_venta_deleted_at_venta_updated_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraImportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            ("CONFLICTO", "Conflicto Detectado"),
                            ("PROCESADO", "Procesado y Confirmado"),
                            ("IGNORADO", "Ignorado Manualmente"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de la Importación",
                    ),
                ),
                (
                    "datos_fila_original",
                    models.JSONField(
                        verbose_name="Datos Originales de la Fila del Excel"
                    ),
                ),
                (
                    "detalles_conflicto",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Detalles del Conflicto Detectado",
                    ),
                ),
                (
                    "fecha_importacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Importación"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "producto_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "proveedor_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cantidad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "precio_compra_unitario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crud_app.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crud_app.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra Importada",
                "verbose_name_plural": "Compras Importadas",
            },
        ),
        migrations.CreateModel(
            name="VentaImportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            ("CONFLICTO", "Conflicto Detectado"),
                            ("PROCESADO", "Procesado y Confirmado"),
                            ("IGNORADO", "Ignorado Manualmente"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de la Importación",
                    ),
                ),
                (
                    "datos_fila_original",
                    models.JSONField(
                        verbose_name="Datos Originales de la Fila del Excel"
                    ),
                ),
                (
                    "detalles_conflicto",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Detalles del Conflicto Detectado",
                    ),
                ),
                (
                    "fecha_importacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Importación"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "producto_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cliente_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cantidad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "precio_venta",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crud_app.cliente",
                    ),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crud_app.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta Importada",
                "verbose_name_plural": "Ventas Importadas",
            },
        ),
    ]
