# Generated by Django 5.2.8 on 2025-11-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0012_compraimportada_ventaimportada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conflicto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_modelo",
                    models.CharField(
                        choices=[
                            ("PRODUCTO", "Producto"),
                            ("CLIENTE", "Cliente"),
                            ("PROVEEDOR", "Proveedor"),
                            ("VENTA", "Venta"),
                            ("COMPRA", "Compra"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Modelo",
                    ),
                ),
                (
                    "id_borrado",
                    models.PositiveIntegerField(verbose_name="ID del Elemento Borrado"),
                ),
                (
                    "id_existente",
                    models.PositiveIntegerField(
                        verbose_name="ID del Elemento Existente (Conflicto)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Resolución"),
                            ("RESUELTO_RESTAURAR", "Resuelto (Restaurado)"),
                            ("RESUELTO_IGNORAR", "Resuelto (Ignorado)"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado del Conflicto",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Detección"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "notas_resolucion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Resolución"
                    ),
                ),
                (
                    "detectado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflictos_detectados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Detectado por",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflictos_resueltos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resuelto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflicto de Conciliación",
                "verbose_name_plural": "Conflictos de Conciliación",
                "ordering": ["-fecha_deteccion"],
            },
        ),
    ]
