# Generated by Django 5.2.8 on 2025-11-22 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0013_conflicto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproducto",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre del Producto"),
        ),
        migrations.AlterField(
            model_name="historicalproveedor",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre del Proveedor"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre del Producto"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre del Proveedor"),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("email",),
                name="unique_active_cliente_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("nombre",),
                name="unique_active_producto_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="proveedor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("nombre",),
                name="unique_active_proveedor_nombre",
            ),
        ),
    ]
