# Generated by Django 5.2.8 on 2025-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0014_alter_cliente_email_alter_historicalcliente_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ruc",
            field=models.CharField(
                blank=True,
                help_text="Registro Único de Contribuyentes (11 dígitos)",
                max_length=11,
                null=True,
                verbose_name="RUC",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="factura",
            field=models.CharField(
                blank=True,
                help_text="Número de factura de la compra",
                max_length=50,
                null=True,
                verbose_name="Número de Factura",
            ),
        ),
        migrations.AddField(
            model_name="historicalcliente",
            name="ruc",
            field=models.CharField(
                blank=True,
                help_text="Registro Único de Contribuyentes (11 dígitos)",
                max_length=11,
                null=True,
                verbose_name="RUC",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompra",
            name="factura",
            field=models.CharField(
                blank=True,
                help_text="Número de factura de la compra",
                max_length=50,
                null=True,
                verbose_name="Número de Factura",
            ),
        ),
        migrations.AddField(
            model_name="historicalproveedor",
            name="ruc",
            field=models.CharField(
                blank=True,
                help_text="Registro Único de Contribuyentes (11 dígitos)",
                max_length=11,
                null=True,
                verbose_name="RUC",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="ruc",
            field=models.CharField(
                blank=True,
                help_text="Registro Único de Contribuyentes (11 dígitos)",
                max_length=11,
                null=True,
                verbose_name="RUC",
            ),
        ),
    ]
